### ISSUE TITLE
Azuredevops resource kit for azure Api management will work with Azure CLI and bash?

### ISSUE THREAD

**Issue by vivuu1989** [Azure/api-management-policy-snippets#121]
We have linux based agents in azure devops and looking for  a way to use the creatioor executor alone to create policy creation APIM manager . is this can be achieved using the the Devops resource kit ?

**Comment by mikebudzynski** [comment]
Merging into #120. @vivuu1989 - please provide more details in the other thread. Note that the DevOps Resource Kit is deprecated as per the statement in the readme file: https://github.com/Azure/azure-api-management-devops-resource-kit.
