### ISSUE TITLE
stop global level policy execution at operation level

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/api-management-policy-snippets#14]
This is in context of azure api management azure service. New ui changes in azure has changed behavior of policy executions i believe.

i have one policy for jwt-validate set at global level for all apis.

recently i had to add new api which doesnt need jwt validation but certificate authentication.

so in apim i created new api, product and added certificate authentication policy at product level.

when i run my api then jwt policy is also firing. How can i stop it from executing in this case. i removed but it stopped global + product level policy.

i want stop execution of global policy but i want product level policy to execute.

please advise.

**Comment by vladvino** [comment]
Global policies affect all existing and new APIs. Your options are not to define vlaidate-jwt at the global scope or define it conditionally based on requested API/product by using choose policy. In the future, please use http://aka.ms/apimso for questions and issues not related to policy examples.
