### ISSUE TITLE
@mikebudzynski, I couldn't add an issue in the Azure API Management repository. So, added the issue here. We are still not able to use policy expression in the rate-limit-by-key policy. I have attached the error screenshot for your reference.

### ISSUE THREAD

**Issue by dibyaranjanjll** [Azure/api-management-policy-snippets#67]
@mikebudzynski, I couldn't add an issue in the Azure API Management repository. So, added the issue here. We are still not able to use policy expression in the rate-limit-by-key policy. I have attached the error screenshot for your reference.

Error: **Error in element 'rate-limit-by-key' on line 24, column 10: The 'calls' attribute is invalid - The value '@((int)context.Variables["api.NamedValue.Config.Json.Cache.Duration"])' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:int' - The string '@((int)context.Variables["api.NamedValue.Config.Json.Cache.Duration"])' is not a valid Int32 value.**

![image](https://user-images.githubusercontent.com/87515814/131089138-35bbd31a-abfd-4c24-84f4-c752833dc098.png)

_Originally posted by @dibyaranjanjll in https://github.com/Azure/api-management-developer-portal/issues/1424#issuecomment-906989082_

**Comment by adrianhall** [comment]
Not a problem in this repository.
